services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: developer/php
        container_name: example_app_dev
        restart: unless-stopped
        ports:
            - 5173:5173
        environment:
            TZ: 'America/Sao_Paulo'
        volumes:
            - ../:/var/www:cached
        networks:
            - private_network
            
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        build: developer/nginx
        container_name: example_web_dev
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        environment:
            TZ: 'America/Sao_Paulo'
        volumes:
            - ../:/var/www
        depends_on:
            - php
        networks:
            - private_network

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    # phpmyadmin:
    #     build: ./production/phpmyadmin
    #     container_name: example_phpmyadmin
    #     restart: unless-stopped
    #     ports:
    #         - "8080:80"
    #         - "4443:443"
    #     environment:
    #         PMA_HOST: mariadb
    #         PMA_PORT: 3306
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}   
    #         TZ: 'America/Sao_Paulo'
    #         APP_HOST: ${APP_HOST}          
    #     #volumes:
    #     # - ./developer/phpmyadmin/sessions:/sessions
    #     depends_on:
    #         - mariadb
    #     networks:
    #         - private_network

    #####################################################################################################
    # DATABASE (MariaDB)
    #####################################################################################################
    # mariadb:
    #     image: mariadb
    #     container_name: example_mariadb
    #     restart: unless-stopped
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./production/mariadb/data:/var/lib/mysql
    #         - ./production/mariadb/logs:/var/log/mysql
    #         - ./production/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - ./production/mariadb/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_DATABASE: ${DB2_DATABASE:-laravel}
    #         MYSQL_ROOT_PASSWORD: ${DB2_PASSWORD:-root}
    #         MYSQL_PASSWORD: ${DB2_PASSWORD:-userpass}
    #         MYSQL_USER: ${DB2_USERNAME:-username}
    #     networks:
    #         - private_network

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    # mysql:
    #     image: mysql:8.1
    #     container_name: example_mysql_dev
    #     restart: unless-stopped
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./developer/mysql/data:/var/lib/mysql
    #         - ./developer/mysql/logs:/var/log/mysql
    #         - ./developer/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - ./developer/mysql/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE:-laravel}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    #         MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
    #         MYSQL_USER: ${DB_USERNAME:-username}
    #         TZ: 'America/Sao_Paulo'
    #     networks:
    #         - private_neto work

    ###################################################################################################
    # PostgreSQL
    ###################################################################################################
    # pgsql:
    #     image: postgres:16
    #     container_name: example_pgsql_dev
    #     restart: unless-stopped
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - ./developer/pgsql/data:/var/lib/postgresql/data
    #         - ./developer/pgsql/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_USER=${DB3_USERNAME:-username}
    #         - POSTGRES_PASSWORD=${DB3_PASSWORD:-root}
    #         - POSTGRES_DB=${DB3_DATABASE:-laravel}
    #     networks:
    #         - private_network

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: example_pgadmin_dev
    #     restart: unless-stopped
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=${DB3_USERNAME:-username@gmail.com}
    #         - PGADMIN_DEFAULT_PASSWORD=${DB3_PASSWORD:-root}
    #     depends_on:
    #         - pgsql
    #     networks:
    #         - private_network

    ####################################################################################################
    # SQL Server
    ####################################################################################################  
    # sqlsrv:
    #     build: ./developer/sqlsrv
    #     restart: unless-stopped
    #     container_name: example_sqlsrv_dev
    #     environment:
    #         ACCEPT_EULA: 'Y'
    #         MSSQL_SA_PASSWORD: ${DB4_PASSWORD:-<YourStrong@Passw0rd>}
    #         MSSQL_TCP_PORT: ${DB4_PORT:-1433} 
    #         MSSQL_DATA_DIR: /var/opt/mssql/data
    #         MSSQL_PID: 'Developer' 
    #         #MSSQL_PID: "Express"
    #         MSSQL_LC_COLLATION: "Latin1_General_CI_AS"
    #         MSSQL_LANG: "pt_br"
    #     ports: 
    #         - "1433:1433"
    #     volumes:
    #         - ./developer/sqlsrv/data/data:/var/opt/mssql/data
    #         - ./developer/sqlsrv/data/log:/var/opt/mssql/log
    #         - ./developer/sqlsrv/data/secrets:/var/opt/mssql/secrets 
    #     networks:
    #         - private_network

    ####################################################################################################
    # Docker Workspace Network
    #################################################################################################### 
networks:
    private_network:
        driver: bridge